---
- hosts: my-instance
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull Docker image
      docker_image:
        name: devcenter14/tf-project:latest

    - name: Run Docker container
      docker_container:
        name: my-app
        image: devcenter14/tf-project:latest
        state: started
        ports:
          - "3000:3000"
