steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/big-query-406006/testreact-app', '.']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['container', 'clusters', 'autopilot-cluster-1', '--region', 'us-central1']
  
logsBucket: 'gs://logsbuild'
