name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: 
        echo ${{ secrets.PASSWORD }} ${{ secrets.USERNAME }} 


    #- name: Build and push Docker image
     # run: |
     #     docker build -t ${{ secrets.USERNAME }}/tf-project:latest .
     #     docker push ${{ secrets.USERNAME }}/tf-project:latest

        
